apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "neo4j.name" . }}
    component: core
  name: "{{ template "neo4j.fullname" . }}"
spec:
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
  ports:
    - name: http
      port: 7474
      protocol: TCP
      targetPort: 7474
  
    - name: "7687-tcp"
      port: 7687
      protocol: TCP
      targetPort: bolt

  selector:
    app: {{ template "neo4j.name" . }}
    release: {{ .Release.Name | quote }}
    component: core
  type: "{{ .Values.service.type }}"
